name: Manual Deployment

on:
  workflow_dispatch: # Enable manual triggering
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'production'
        type: choice
        options:
          - production
          - staging

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Deploy to Server
        # Replace this with your actual deployment action or script
        # For example, using SamKirkland/FTP-Deploy-Action:
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: ./
          port: 21
          protocol: ftp
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            **/scss/**
            **/*.scss
            **/*.map
            iploy.yml
            deploy.yml
